# Generated by GNUN (update-localized-urls) on Thu Apr 26 10:07:55 EDT 2012

localized-url-sources :=
localized-url-sources += philosophy/categories
define philosophy/categories-localized-urls
/philosophy/category.png
endef
localized-url-sources += licenses/quick-guide-gplv3
define licenses/quick-guide-gplv3-localized-urls
/licenses/quick-guide-gplv3-compatibility.png
endef
localized-url-sources += licenses/gpl-faq
define licenses/gpl-faq-localized-urls
/licenses/template-diagram.png
endef
localized-url-sources += server/body-include-2
define server/body-include-2-localized-urls
/graphics/day-against-drm-2012.png
endef
localized-url-sources += education/edu-software-tuxpaint
define education/edu-software-tuxpaint-localized-urls
/education/misc/tuxpaint-start-sm.png \
/education/misc/tuxpaint-start.png
endef
