# Generated by GNUN (update-localized-urls) on Mon Feb 27 09:53:44 EST 2012

localized-url-sources :=
localized-url-sources += philosophy/categories
define philosophy/categories-localized-urls
/philosophy/category.png
endef
localized-url-sources += licenses/quick-guide-gplv3
define licenses/quick-guide-gplv3-localized-urls
/licenses/quick-guide-gplv3-compatibility.png
endef
localized-url-sources += licenses/gpl-faq
define licenses/gpl-faq-localized-urls
/licenses/template-diagram.png
endef
localized-url-sources += education/edu-software-tuxpaint
define education/edu-software-tuxpaint-localized-urls
/education/misc/tuxpaint-start-sm.jpg \
/education/misc/tuxpaint-start.jpg
endef
