# Generated by GNUN (update-localized-urls) on Tue May 15 09:52:57 EDT 2012

localized-url-sources :=
localized-url-sources += philosophy/categories
define philosophy/categories-localized-urls
/philosophy/category.png
endef
localized-url-sources += licenses/quick-guide-gplv3
define licenses/quick-guide-gplv3-localized-urls
/licenses/quick-guide-gplv3-compatibility.png
endef
localized-url-sources += licenses/gpl-faq
define licenses/gpl-faq-localized-urls
/licenses/template-diagram.png
endef
localized-url-sources += education/education
define education/education-localized-urls
/education/rms-education-es.ogv
endef
localized-url-sources += education/edu-software-tuxpaint
define education/edu-software-tuxpaint-localized-urls
/education/misc/tuxpaint-start-sm.png \
/education/misc/tuxpaint-start.png
endef
