<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet  version="1.0" 
		 xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
		 xmlns:html="http://www.w3.org/1999/xhtml">

    <!-- (C) Free Software Foundation 2004
	 This program is free software; you can redistribute it and/or modify
	 it under the terms of the GNU General Public License as published by 
	 the Free Software Foundation; either version 2, or (at your option) 
	 any later version. 
	 This program is distributed in the hope that it will be useful, 
	 but WITHOUT ANY WARRANTY; without even the implied warranty of 
	 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
	 GNU General Public License for more details. 
	 You should have received a copy of the GNU General Public License 
	 along with this program; see the file COPYING.  If not, write to the 
	 Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, 
	 Boston, MA 02110-1301, USA. 
      -->

    <xsl:import href="whatsnew_translations.xslt"/>
    <xsl:import href="whatsnew_include.xslt"/>

    <!-- Script to convert the whatsnew database into the whatsnew.html page.
	 This is run by a Makefile in the ../rss directory.
      -->
    <xsl:output method="xml" indent="yes"	
		doctype-public="-//W3C//DTD XHTML 1.0 Strict//EN"
		doctype-system="http://www.w3.org/TR/xhtml1/DTD/xhtml-strict.dtd"/>

    <xsl:template match="/">
	<html xml:lang="en">
	    <head>
		<title>Novidades do Projeto GNU - Projeto GNU - Fundação pelo Software Livre (FSF)</title>
		<link rev="made" href="mailto:webmasters@www.gnu.org" />
		<link rel="stylesheet" type="text/css" href="/gnu.css" />
		<xsl:comment>
		    Webmasters: Do not Edit this file. Edit the news database instead.
		    See the webmaster guide.
		</xsl:comment>
	    </head>
	    <body>
		<h3>Novidades do Projeto GNU</h3>

		<p>
		    <a href="/graphics/agnuhead.html">
			<img src="/graphics/gnu-head-sm.jpg"
			     alt=" [imagem da cabeça de um GNU] "
			     width="129" height="122" />
		    </a>
		</p>
  
		<p>
		    [<xsl:apply-templates select="$translations/whatsnew_translations"/>]
		</p>

		<!-- Coming Events changes regularly and this is another good place to  -->
		<!-- link from and catch people's eye.  -len tower 19Feb00 -->
		<!-- The link is currently dead, due to unfixed, faulty -->
		<!-- replication.  I have replaced it with a temporary file
		     <a href="/events.html"><strong>Coming Events</strong></a>
		     -->
		<p><a href="/events.tmp.html"><strong>Próximos Eventos</strong></a>
		    | <a href="/keepingup.html"><strong>Mantendo o Suporte ao GNU e à FSF</strong></a>
		    | <a href="/press/press.html"><strong>Informações para a Imprensa</strong></a>
		    e <a href="/press/press.html#releases"><strong>Press Releases</strong></a>
		</p>    


		<!-- Every April or May split the prior year's entries out into a separate -->
		<!-- file, so the download time for this file isn't too long. -->
		
		<!-- Please make entries so the newest are at the top -->
		
		<!-- If you add something which is unusually interesting here, please -->
		<!-- consider sending an announcement to info-gnu@gnu.org -->

		<xsl:apply-templates select="items/item"/>

		<h4>Novidades dos Anos Anteriores</h4>
		<ul>
		    <!-- Please add years so the latest is first -->
		    <li><a href="/server/03whatsnew.html"><strong>2003</strong></a></li>
		    <li><a href="/server/02whatsnew.html"><strong>2002</strong></a></li>
		    <li><a href="/server/01whatsnew.html"><strong>2001</strong></a></li>
		    <li><a href="/server/00whatsnew.html"><strong>2000</strong></a></li>
		    <li><a href="/server/99whatsnew.html"><strong>1999</strong></a></li>
		    <li><a href="/server/98whatsnew.html"><strong>1998</strong></a></li>
		    <li><a href="/server/97whatsnew.html"><strong>1997</strong></a></li>
		    <li><a href="/server/96whatsnew.html"><strong>1996</strong></a></li>
		</ul>
		<br />

		<div class="copyright">

		    <p>Voltar para a <a href="/home.pt-br.html">página principal do Projeto GNU</a>.</p>

		    <p>Por favor envie questões sobre a FSF e/ou o GNU para 
			<a href="mailto:gnu@gnu.org"><em>gnu@gnu.org</em></a>. Também há  
			<a href="/home.pt-br.html#ContactInfo">outros meios de contactar</a> a FSF.  <br/>
			Por favor avise sobre links quebrados e outras correções (ou sugestões) para 
			<a href="mailto:webmasters@gnu.org"><em>webmasters@gnu.org</em></a>.
		    </p>

		    <p>Copyright (C) 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004 Free Software Foundation, Inc.,
			51 Franklin St, Fifth Floor, Boston, MA  02110,  USA<br />
			A cópia fiel e distribuição deste artigo, em sua totalidade, é permitida em qualquer meio, desde que esta nota seja preservada.
		    </p>

		    <p>Atualizada:
			<!-- timestamp start -->
			<xsl:comment> timestamp start </xsl:comment>
			$Date: 2008/03/20 13:56:59 $ $Author: yavor $
			<xsl:comment> timestamp end </xsl:comment>
			<!-- timestamp end -->
		    </p>
                    <!-- translated from cvs version 1.3 -->
                    <p>Traduzida por: Fernando Lozano &lt;fernando@lozano.eti.br&gt;</p>

		</div>
	    </body>
	</html>
    </xsl:template>

</xsl:stylesheet>
