<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet  version="1.0"
		 xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
		 xmlns:html="http://www.w3.org/1999/xhtml">

    <!-- (C) Free Software Foundation 2004
	 This program is free software; you can redistribute it and/or modify
	 it under the terms of the GNU General Public License as published by
	 the Free Software Foundation; either version 2, or (at your option)
	 any later version.
	 This program is distributed in the hope that it will be useful,
	 but WITHOUT ANY WARRANTY; without even the implied warranty of
	 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	 GNU General Public License for more details.
	 You should have received a copy of the GNU General Public License
	 along with this program; see the file COPYING.  If not, write to the
	 Free Software Foundation, Inc., 51 Franklin St, Fifth Floor,
	 Boston, MA 02110-1301, USA.
      -->

    <xsl:import href="whatsnew_translations.xslt"/>
    <xsl:import href="whatsnew_include.xslt"/>

    <!-- Script to convert the whatsnew database into the whatsnew.html page.
	 This is run by a Makefile in the ../rss directory.
      -->
    <xsl:output method="xml" indent="yes"
		doctype-public="-//W3C//DTD XHTML 1.0 Strict//EN"
		doctype-system="http://www.w3.org/TR/xhtml1/DTD/xhtml-strict.dtd"/>

    <xsl:template match="/">
	<html xml:lang="pl">
	    <head>
		<title>Aktualności Projektu GNU - Projekt GNU - Fundacja Wolnego Oprogramowania (FSF)</title>
			<meta http-equiv="content-type" content="text/html; charset=utf-8" />
			<link rel="stylesheet" type="text/css" href="/gnu.css" />
			<link rev="made" href="mailto:webmasters@gnu.org" />
			<link rev="translated" href="mailto:web-translators-pl@gnu.org" />
			<xsl:comment> transl.: wkotwica</xsl:comment>
		<xsl:comment>
		    Webmasters: Do not Edit this file. Edit the news database instead.
		    See the webmaster guide.
		</xsl:comment>
	    </head>
	    <body>
		<h3>Nowości Projektu GNU</h3>

		<p>
		    <a href="/graphics/agnuhead.pl.html">
			<img src="/graphics/gnu-head-sm.jpg"
			     alt=" [rysunek głowy GNU] "
			     width="129" height="122" />
		    </a>
		</p>

		<p>
		    [<xsl:apply-templates select="$translations/whatsnew_translations"/>]
		</p>

		<!-- Coming Events changes regularly and this is another good place to  -->
		<!-- link from and catch people's eye.  -len tower 19Feb00 -->
		<!-- The link is currently dead, due to unfixed, faulty -->
		<!-- replication.  I have replaced it with a temporary file
		     <a href="/events.html"><strong>Coming Events</strong></a>
		     -->
		<p><a href="/events.tmp.html"><strong>Zbliżające się wydarzenia</strong></a>
		    | <a href="/keepingup.html"><strong>Na bieżąco z GNU i FSF</strong></a>
		    | <a href="/press/press.html"><strong>Informacje dla prasy</strong></a>
		    | <a href="/press/press.html#releases"><strong>Komunikaty prasowe</strong></a>
		</p>


		<!-- Every April or May split the prior year's entries out into a separate -->
		<!-- file, so the download time for this file isn't too long. -->

		<!-- Please make entries so the newest are at the top -->

		<!-- If you add something which is unusually interesting here, please -->
		<!-- consider sending an announcement to info-gnu@gnu.org -->

		<xsl:apply-templates select="items/item"/>

		<h4>Aktualności z poprzednich lat</h4>
		<ul>
		    <!-- Please add years so the latest is first -->
		    <li><a href="/server/03whatsnew.html"><strong>2003</strong></a></li>
		    <li><a href="/server/02whatsnew.html"><strong>2002</strong></a></li>
		    <li><a href="/server/01whatsnew.html"><strong>2001</strong></a></li>
		    <li><a href="/server/00whatsnew.html"><strong>2000</strong></a></li>
		    <li><a href="/server/99whatsnew.html"><strong>1999</strong></a></li>
		    <li><a href="/server/98whatsnew.html"><strong>1998</strong></a></li>
		    <li><a href="/server/97whatsnew.html"><strong>1997</strong></a></li>
		    <li><a href="/server/96whatsnew.html"><strong>1996</strong></a></li>
		</ul>
		<br />

		<div class="copyright">

		    <p>Powrót do <a href="/home.pl.html">strony głównej Projektu GNU</a>.</p>
		    
		    <p>Pytania dotyczące GNU i FSF prosimy kierować na adres
			<a href="mailto:gnu@gnu.org"><em>gnu@gnu.org</em></a>.
			Istnieją także
			<a href="/home.pl.html#ContactInfo">inne sposoby skontaktowania się</a>
			z&#160;FSF.
			<br />
			Informacje o niedziałających odnośnikach oraz inne poprawki
			(lub propozycje) prosimy wysyłać na adres
			<a href="mailto:webmasters@gnu.org"><em>webmasters@gnu.org</em></a>.
		    </p>

		    <p>Copyright (C) 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006 Free Software Foundation, Inc.,
			51 Franklin St, Fifth Floor, Boston, MA  02110,  USA<br />
			<br />
			Verbatim copying and distribution of this entire article is
			permitted in any medium, provided this notice is preserved.
			<br />
			Zezwala się na wykonywanie i dystrybucję wiernych kopii tego tekstu,
			niezależnie od nośnika, pod warunkiem zachowania niniejszego zezwolenia.
		    </p>

		    <p>Atualizowane:
			<!-- timestamp start -->
			<xsl:comment> timestamp start </xsl:comment>
			$Date: 2006/06/27 16:13:42 $ $Author: wkotwica $
			<xsl:comment> timestamp end </xsl:comment>
			<!-- timestamp end -->
		    </p>

		</div>
	    </body>
	</html>
    </xsl:template>

</xsl:stylesheet>
