# /etc/bashrc

# System wide functions and aliases
# Environment stuff goes in /etc/profile

# For some unknown reason bash refuses to inherit
# PS1 in some circumstances that I can't figure out.
# Putting PS1 here ensures that it gets loaded every time.
PS1="[\u@\h \W]\\$ "
#---------------------------------------------------------
#
# *** Inicio de la modificación de TutorialLinux. *** 
#
# Inicializamos un PATH, para en el que a partir de ahora
# no haga falta escribir ./programa, porque ya estará en
# el PATH
# Esta opción de poner './', no es recomendable si varios
# usuarios ajenos al sistema acceden a su máquina (telnet)
# o procure que sea la última opción de path
export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/X11R6/bin:/root/bin:/sbin:/usr/bin:/usr/local/bin:/opt/kde:./
#
# Usar 'F' será buena idea para los usuarios que se conecten
# de forma remota (por telnet) en el alias del comando 'ls'
#

alias ls='ls --color -shF'
alias rd='rmdir'
alias cp='cp -i -v'
 alias md='mkdir'
alias mv='mv -i -v'
alias rm='rm -i'
alias cd..='cd ..'
alias dir='dir --color -hFs'
alias vdir='vdir --color -shF'
alias cls='clear'
alias joe='joe -asis'
alias less='less -r'
alias df="df -h"
alias du="du -h"

#
# ALIAS para montar las unidades, en vez de escribir mount -t...
# escribes su alias y montas la unidad, luego sólo cambia de unidad
# Te recordamos que los directorios mencionados en /mnt, deben de existir
# -1disco, 2disco, cdrom, floppy...-, así como hda1 deberá ser una
# unidad para windows con vfat, o sda1 si es SCSI...
#
# Cuando tengas configurado tu fichero /etc/fstab, puede ser que
# te convenga sustituir los alias, y quede por ejemplo así:
# alias A1='mount /dev/hda1'
# Ya que en el fichero /etc/fstab, tendrás los modos por defecto.
#
# Te recomendamos crees los directorios en /mnt/
#
alias WFLOPPY='mount -t vfat /dev/fd0 /mnt/floppy' # (W)in and DOS floppys
alias FLOPPY='mount -t ext2 /dev/fd0 /mnt/floppy'  # (L)INUX FLOPPY
alias A1='mount -t vfat /dev/hda1 /mnt/1disco'	   # HD(A1) (Disco duro)
alias B1='mount -t vfat /dev/hdb1 /mnt/2disco'	   # HD(B1) (Disco duro)
alias CDR='mount -t iso9660 /dev/cdrom /mnt/cdrom' # (CDR)om
alias l+='mount -t ext2 /dev/hdb2 /mnt/+linux'	   # +Linux (Particion Linux)
#
# ALIAS para desmontar las unidades
#
alias DFLOPPY='umount /dev/fd0'   # (D)esmontar (cualquier fs) FD(0)
alias DA1='umount /dev/hda1'      # (D)esmontar HD(A1)
alias DB1='umount /dev/hdb1'      # (D)esmontar HD(B1)
alias DCDR='umount /dev/cdrom'    # (D)esmontar (CDR)om
alias Dl+='umount /dev/hdb2'	  # (D)esmontar +Linux
#
# Ejemplo ilustrativo de un 'alias', para usarlo
#
# alias kde='xinit startkde'
#
# Funcionará si el kde está instalado y el path accesible
#
# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*- 
# Cuando uses, por ejemplo: linuxconf, podrás configurar
# tu equipo linux, para que si quieres los usuarios puedan
# montar unidades, entonces, retoca este punto y quita
# el caracter inicial de la balla.
# 
# alias para montar los usuarios las unidades.
# ahora usando el alias: floppy, o cdr, montaremos la unidad.
# 

alias floppy='mount /dev/fd0' 
alias a1='mount /dev/hda1'  
alias b1='mount /dev/hdb1' 
alias cdr='mount /dev/cdrom' 
alias +l='mount /dev/hdb2' 

# 
# desmontar las unidades
# 

alias dfloppy='umount /dev/fd0'
alias da1='umount /dev/hda1'
alias db1='umount /dev/hdb1'
alias dcdr='umount /dev/cdrom'
alias dl+='umount /dev/hdb2'

# 
# *** Fin de la modificación de TutorialLinux. *** 
# 
