#!/bin/bash
#
# Ejemplo de Script para la compilación del núcleo.	Versión Script: 4.2.0 
# Fecha: 26 / Junio / 1.999
#
#	Primero deberás hacer "manualmente" un  make menuconfig  ó
#	make xconfig, una vez configurado, escribe: ./CompilaNucleo
#	y espera el resultado.
#
#	Este script, básicamente lo único que hace es:
#
#	make dep
#	make clean
#	make zImage
#	Y algún adorno más para hacerlo mas elegante.
#
clear
#
echo "******************************************************************"

if [ -f /usr/src/linux/arch/i386/boot/zImage ]; then
 echo
 echo "Existe ya un nucleo compilado llamado zImage en el directorio: "
 echo -n "/usr/src/linux/arch/i386/boot/ ¿Deseas continuar? [s] :"
 read SoN
 if expr "$SoN" == "n"
   then
    echo
    echo "Proceso detenido, haz copia o mueve el fichero."
    echo
    exit
 fi
fi

if [ -f /usr/src/linux/arch/i386/boot/bzImage ]; then
 echo
 echo "Existe ya un nucleo compilado llamado bzImage en el directorio: "
 echo -n "/usr/src/linux/arch/i386/boot/ ¿Deseas continuar? [s] :"
 read SoN
 if expr "$SoN" == "n"
   then
    echo
    echo "Proceso detenido, haz copia o mueve el fichero."
    echo
    exit
 fi
fi

  clear
  #
  echo "******************************************************************"
  echo "COMPROBANDO DEPENDENCIAS..."
  echo
  make dep
  echo
  echo 7 segundos de espera...
  sleep 7
  clear
  echo "******************************************************************"
  echo LIMPIANDO BASURA... 
  make clean
  echo
  echo 7 segundos de espera...
  sleep 7
  clear
  echo "******************************************************************"
  echo "CON UN POCO DE SUERTE, COMPILANDO EL NÚCLEO..."
  echo "Estáte atento a los posibles mensajes de error..."
  echo 
  make bzImage
  echo 
  #
  # Comprobamos si existe el fichero
  #
  if [ -f /usr/src/linux/arch/i386/boot/bzImage ]; then	
	echo
	  echo "******************************************************************"
	printf "\a"
	echo "¡¡ TENEMOS NUCLEO NUEVO !!"
	sleep 1
	echo
	printf "\a"
        echo "¡¡ TENEMOS NUCLEO NUEVO !!"
	sleep 1
	echo
	printf "\a"
        echo "¡¡ TENEMOS NUCLEO NUEVO !!"
        printf "\a"
        printf "\a"
        echo "******************************************************************"
	printf "\a"
                echo "INSTALACION/PRECONFIGURACION AUTOMÁTICA: (RECOMENDADO SOLO PARA PRINCIPIANTES)"
		echo
		echo "CompilaNucleo puede tratar de INSTALAR Y CONFIGURAR el nuevo núcleo, siempre y"
		echo "cuando en el fichero /etc/lilo.conf, exista (vmlinuz) y esté el primero en la "
		echo "lista de ejecución. Te lo vamos a mostrar para que tu decidas. Si apareciera: "
		echo
		echo "image=/boot/bzImage"
		echo "image=/boot/vmlinuz"
		echo
		echo "NO HARÁ NADA, ya que el fichero sustituido será vmlinuz, y has de copiar el "
		echo "nuevo núclo via: cp -v /usr/src/linux/arch/i386/boot/bzImage /boot. Posterior-"
		echo "mente deberás ejecutar el comando 'lilo' para que surga efecto. Si la lista "
		echo "apareciera al reves, no deberías hacer nada ya que COMPILANUCLEO ha hecho eso "
		echo "por tí. MONSTRANDO..."
        	echo
		grep image /etc/lilo.conf		
                echo
		echo -n "¿Quieres que automáticamente lo instale y preconfigure?: (s/n) [s]"
                read Preconf

                if expr "$Preconf" == "s"
                then
                        make bzlilo
			echo "Moviendo:..  /System.map    a:   /boot/"
			mv -fv /System.map /boot/
			echo "Moviendo:..  /vmlinuz   a:   /boot/"
			mv -fv /vmlinuz /boot/
                fi
		
		printf "\a"
		echo "******************************************************************"
		printf "\a"
		echo "¿ Quieres que automáticamente haga: "
		echo -n " make modules  y  make modules_install ? [s] : "
		read Querer

		if expr "$Querer" == "n"
                then
			echo "SALIENDO..."
			exit 1
		else
                        echo "TRABAJANDO..."
                        make modules
                        make modules_install
  echo "******************************************************************"
			echo
			echo "Ahora lee la sección del tutorial:"
			echo "Herramientas y administración/Compilando el núcleo/Cómo arrancar con él."
			echo
		fi

  else
        printf "\a"
	echo "¡¡ HA HABIDO ERRORES DE COMPILACION, NO TENEMOS NUEVO NUCLEO !!"
	sleep 1
	printf "\a"
	echo -n "Pulse [intro] para continuar...."
 	read
	echo
	echo "Recomendación: haz: make mrproper, make menuconfig/xconfig y"
	echo "./CompilaNucleo otra vez o escribe ahora make para continuar"
	echo "la compilación del nucleo."
	echo
	echo "Desaconsejamos: intentar cargar el fichero de configuración"
	echo "del nucleo que hubieras podido guardar, y compilar de nuevo."
	echo
fi
#
