<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet  version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

    <xsl:output method="xml" omit-xml-declaration="yes"/> 

    <xsl:template match="/items">
        <xsl:comment> DO NOT EDIT THIS FILE BY HAND </xsl:comment>
        <xsl:comment> SEE /server/standards/README.webmastering.html#polnews </xsl:comment>
	<xsl:apply-templates select=".//news[../@flash = 'yes']"/>
    </xsl:template>

    <xsl:template match="news">
	<xsl:if test="position() &lt; 4">
	    <p><xsl:copy-of select="node()"/></p><xsl:text>
</xsl:text>
	</xsl:if>
    </xsl:template>

</xsl:stylesheet>
