<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE xsl:stylesheet [<!ENTITY nbsp "&#160;">
			  <!ENTITY eur "&#128;">]>

<xsl:stylesheet version="1.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

  <xsl:output method="html"
	    encoding="ISO-8859-1"
	    doctype-public="-//W3C//DTD HTML 4.0 Transitional//EN"
	    doctype-system="http://www.w3.org/TR/REC-html40/loose.dtd"
	    indent="yes"
	    />

  <xsl:param name="gnues">/</xsl:param>
  <xsl:param name="fsffrance">http://france.fsfeurope.org</xsl:param>
  <xsl:param name="fsfeurope">http://www.fsfeurope.org</xsl:param>
  <xsl:param name="fsf">http://www.fsf.org</xsl:param>
  <xsl:param name="gnu">http://www.gnu.org</xsl:param>
  <xsl:param name="filebase">nofile.html</xsl:param>
  <xsl:param name="path">nofile.html</xsl:param>
  <xsl:param name="langlinks">[ English ]</xsl:param>

  <xsl:template match="/">
    <xsl:copy>
      <xsl:apply-templates select="@*|node()"/>
    </xsl:copy>
  </xsl:template>

  <xsl:template match="/html/body">
    <body topmargin="0" bottommargin="0" leftmargin="0" rightmargin="0" marginheight="0" marginwidth="0">
      <xsl:comment>

	DO NOT MODIFY THIS DOCUMENT. IT WAS GENERATED BY XSLT PROCESSING
	AND YOUR MODIFICATIONS WILL BE LOST. THE SOURCE OF THE DOCUMENT
	IS IN THE .xhtml FILE USE make all TO REGENERATE

      </xsl:comment>
      <xsl:apply-templates select="node()"/>
    </body>
  </xsl:template>

  <xsl:template match="/html/head">
    <head>
      <link rel="stylesheet" type="text/css" href="{$gnues}/gnues.css" />
      <xsl:apply-templates select="@*|node()"/>
    </head>
  </xsl:template>

  <xsl:template match="/html[@lang='es']/body/div">
    <table cellspacing="0" cellpadding="1" width="100%" border="0"> 
      <tr valign="middle"> 
	  <td class="newstext">
<!--	    &nbsp;&nbsp;
            <a href="index.html">GNU España</a> -->
          </td>
          <td class="newstext" align="right">
	    <a href="http://www.fsf.org/home.es.html">FSF</a>
            &nbsp;&nbsp;|&nbsp;&nbsp;
	    <a href="http://www.gnu.org/home.es.html">GNU</a>
	    &nbsp;&nbsp;|&nbsp;&nbsp;
	    <a href="http://www.fsfeurope.org/index.es.html">FSF Europa</a>
            &nbsp;&nbsp;|&nbsp;&nbsp;
	    <a href="http://www.ansol.org">ANSOL</a><br/>

	  </td>
       </tr>
    </table>

    <!-- Top menu line -->
    <table width="100%" border="0" cellspacing="0" cellpadding="4">
      <tr>
	<td class="TopTitle">

<!-- Barra Superior -->
<!--	  &nbsp;<a href="{$fsffrance}/index.fr.html">Francia</a> |
	    Alemania -->
	</td>
      </tr>
    </table>

    <!-- Title bar -->
    <table width="100%" border="0" cellspacing="0" cellpadding="8">
	<tr>
	  <td class="TopBody">
	    <a href="http://www.es.gnu.org">
	      <img src="{$gnues}/Images/gnues.png" alt="GNUES Logo"
    border="0" width="259" height="76" align="left"/>
	    </a>
	  </td>
	</tr>
    </table>

    <table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
	<td width="99%" valign="top">
        <div class="content">
        <center>
<!--        <xsl:value-of select="$langlinks" disable-output-escaping="yes"/>-->
        </center>
	<xsl:apply-templates select="@*|node()"/>
	</div>
	</td>
	<!-- Columna de menú. Al lado derecho para que Lynx la vea mejor.  -->
	<td>&nbsp;</td>
	<td valign="top" class="TopBody">
          <table summary="" width="150" border="0" cellspacing="0"
          cellpadding="4">

	<!-- Secciones -->
            <tr><td class="TopTitle" align="center">Secciones</td></tr>
              <tr>
                <td class="TopBody" align="right">
                  <a href="{$gnues}/software/index.html">Software GNU</a><br />
                  <a href="{$gnues}/licencias/index.html">Licencias libres</a><br />
		  <a href="{$gnues}/documentacion/index.html">Documentación</a><br />
		  <a href="{$gnues}/eventos/index.html">Eventos</a><br />

		  <a href="{$gnues}/desarrollo/index.html">Recursos para desarrolladores</a><br />
	          <a href="{$gnues}/cgi-bin/gnueswiki.pl">GnuEsWiki</a><br />
	          <a href="{$gnues}/bugzilla">GnuEsBugzilla</a><br />
	          <a href="{$gnues}/gnuticias">GNUticias</a><br />
		  <a href="{$gnu}/education/education.es.html">Educación</a><br />

                </td>
              </tr>
            <tr>
         <!-- Grupos en GNU España -->
             <td class="TopTitle" align="center">Grupos en GNUes</td>
	     </tr>
	     <tr>
	      <td class="TopBody" align="right">
	        <a href="http://hurd.es.gnu.org">Grupo de usuarios
              españoles de GNU/Hurd</a> <br />
		<a href="http://bee.es.gnu.org">Bee GNU/Hurd, la
              distro española de GNU.</a> <br />
	      </td>
             </tr>
            

            <tr>

	 <!-- El Proyecto GNU -->
             <td class="TopTitle" align="center">El Proyecto GNU</td>
	     </tr>
	     <tr>
	      <td class="TopBody" align="right">
	        <a href="{$gnu}/gnu/thegnuproject.es.html">¿Qué es?</a> <br />
		<a href="{$gnu}/gnu/manifesto.es.html">El Manifiesto GNU</a> <br />
		<a href="{$gnues}/proyecto/paquetes.html">Paquetes Software GNU</a> <br />
		<a href="{$gnues}/proyecto/gnu-linux-faq.html">GNU/Linux vs. Linux</a> <br />
		<a href="{$gnues}/proyecto/personajes.html">Personajes del Proyecto</a> <br />
	        <a href="{$gnu}/philosophy/philosophy.es.html">Filosofía del Proyecto</a> <br />
	        <a href="http://savannah.gnu.org">Savannah</a> <br />
	      </td>
             </tr>

            <tr>
	      
	 <!-- Listas y Foros -->
             <td class="TopTitle" align="center">Listas y Foros</td>
	     </tr>
	     <tr>
	      <td class="TopBody" align="right">
	        <a href="{$gnues}/listasdecorreo.html">Listas de correo</a><br />
	      </td>
             </tr>

            <tr>
	<!-- Mas GNU en España -->
              <td class="TopTitle" align="center">Mas GNU en España</td>
            </tr>
            <tr>
              <td class="TopBody" align="right">
	        <a href="http://gugs.sindominio.net">GUGS</a><br />
		<a href="http://forogugs.sindominio.net">Foro GUGS</a><br />
		<a href="http://www.gnuino.org">GNU en 8 pasos</a><br />

            </td>
            </tr>

             <tr>

	 <!-- Mas Software Libre en España -->
	     <td class="TopTitle" align="center">Mas Software Libre en España</td>
	     </tr>
	     <tr>
	       <td class="TopBody" align="right">
	         <a href="http://alts.homelinux.net">Alternativas Libres</a><br />
               </td>
	     </tr>

            <tr>
	 <!-- Administración -->
              <td class="TopTitle" align="center">Administración</td>
            </tr>
            <tr>
              <td align="right"><br/>
              <a href="{$gnues}/normas_estilo.html"
                  >Guía de Estilo del web</a><br/>
              <a href="{$gnu}/server/standards/"
                  >Estándares GNU</a><br/>

              <br/></td>
            </tr>
          </table>
        </td>
      </tr>
    </table>

    <!-- Bottom line -->
    <table width="100%" border="0" cellspacing="0" cellpadding="2">
      <tr>
	<td class="TopTitle">
          <a href="{$filebase}.xhtml">Fuente XHTML</a>&nbsp;&nbsp;|
          &nbsp;&nbsp;<a href="{$gnues}/gnues.xsl">Página de
    estilo XSL</a><br/>
	</td>
	<td class="TopTitle" align="right">
	  &nbsp;<a href="mailto:webmasters@es.gnu.org"
                  >webmasters@es.gnu.org</a>
        </td>
      </tr>
      <tr>
	<td class="newstext" align="center">
	<font size="-2">
	  Copyright (C) 2002 GNU España<br/>
          Se permite la copia textual y distribución de este artículo en su
	  totalidad, por cualquier medio, siempre y cuando se mantenga esta
	  nota de copyright.
	</font>
	</td>
        <td class="newstext">&nbsp;</td>
      </tr>
    </table>
  </xsl:template> 

  <!-- Template de noticias. jemarch -->
  <xsl:template match="noticia">

<p>
 <table border="0" cellpadding="0" cellspacing="0">
  <tbody>
   <tr class="TopBody" valign="top">
    <td>
      <img src="Images/pix.png" width="5" height="1" alt=" " />
    </td>
    <td class="TopBody" width="10" valign="top">
      <img border="0" width="10" height="13" src="Images/ul.png" alt="(( " />
    </td>
    <td class="TopBody">
	   <xsl:variable name="milink">
	   <xsl:value-of select="@link" />
	   </xsl:variable>
      <a href="{$milink}"><xsl:value-of select="@titulo" /></a> 
      <b> <xsl:value-of select="@fecha" /> </b>
    </td>
    <td width="10" align="right" class="TopBody" valign="top">
      <img border="0" width="10" height="13" src="Images/ur.png" alt=")) " />
    </td>
   </tr>
  </tbody>
 </table>

 <table border="0" cellspacing="0" cellpadding="1" bgcolor="#736199">
  <tbody>
   <tr>
    <td valign="bottom">
     <table border="0" bgcolor="#cacaca" cellspacing="0" cellpadding="3">
      <tbody>
       <tr>
        <td nowrap="1" class="newsinfo">
	   <xsl:variable name="milink">
	   <xsl:value-of select="@link" />
	   </xsl:variable>
           <a href="{$milink}">Artículo completo</a>
        </td>
       </tr>
       <tr>
        <td class="newstext">
          <xsl:value-of select="." />
        </td>
       </tr>
      </tbody>
     </table>
    </td>
   </tr>
  </tbody>
 </table>
</p>


 </xsl:template>
    

  <xsl:template match="@*|node()" priority="-1">
    <xsl:copy>
      <xsl:apply-templates select="@*|node()"/>
    </xsl:copy>
  </xsl:template>

</xsl:stylesheet>
