#! /bin/sh
cd /home/www/html/prep/wrappers-and-scripts/
cp ftp-header.html ../ftp.html
perl /home/www/html/prep/wrappers-and-scripts/ftp_convert.pl ../FTP>> ../ftp.html
cat ftp-eof.html >> ../ftp.html

