@node  Free Software Song, Section Two, freedocumentation, Top
@sp 6
@chapter Free Software Song
@cindex free software song

@tex 
%%  unnumberedfootnote
%%  Since`footnotezzz' uses `thisfootno', set it to nothing.   
\global\let\thisfootno\
\global\def\unnumberedfootnote{\footnotezzz}%
@end tex

@unnumberedfootnote{
@smallformat
Originally written in 1993, this version is part of @emph{Free Software, Free Society: Selected Essays of Richard M. 
Stallman}, 2002, GNU Press (http://www.gnupress.org); ISBN 1-882114-98-1.
@end smallformat
@flushleft
@center Verbatim copying and distribution of this entire article is 
@center permitted in any medium, provided this notice is preserved
@end flushleft
}

@noindent
To the melody of the Bulgarian folk song ``Sodi Moma.''

@image{images/free_software_song}
