@node ads_page, , GNU Free Documentation License, Top
@c -*-texinfo-*-
@c GNU PRESS ADS PAGE 2002
@c This is an add page intended to be placed in the
@c back of a GNU Press book
@c Copyright (C) 2002
@c   Free Software Foundation, Inc.

@c create a page break to make sure it is seperated
@page

@c rename this chapter for the header
@iftex
@def@thischapter{Other Titles From GNU Press}
@end iftex
    @c Change the font size
    @tex
    {\globaldefs = 1 \smallfonts}
    @end tex



@c *************  NEW FROM GNU PRESS  *******************************
@image{gnu_press_ads/newfromgnu,4.8in,1.45in}
@multitable {Column 1 length is this long 0 0 000} {Column 2 length is this long 0 0 000}

@c Row 1, Column 1
@item 
@strong{GNU MDK:}@*@strong{GNU MIX Development Kit}@*@strong{by Jos@'e
Antonio Ortega Ruiz}@*@emph{1-882114-62-0, $16.95}@*@emph{Perfect
bound, trade paper}@*@emph{100 Pages} (Estimate)@*@emph{Publication Date:
July 2002}@*The MIX is a mythical computer designed by Donald Knuth in
his monumental work @emph{The Art Of Computer Programming}. MIXAL, the MIX
Assembly Language, is the assembler language used to program it.  You
can learn about MIX and MIXAL as an introduction to computer
architecture and assembly programming, as a companion to Knuth's book,
or just for fun.  The MIX system was brought to life by Jos@'e Antonio
Ortega Ruiz, who wrote the program following Knuth's design.
@*@*
@strong{The GNU C Programming Tutorial}@*@strong{by Mark Burgess & Ron
Hale-Evans}@*@strong{Edited by Joshua Gay}@*@emph{1-882114-61-2,
$39.00} (Estimate)@*@emph{Lay flat, trade paper}@*@emph{Approx. 350
Pages}@*@emph{Publication Date: September 2002}@*The GNU C Programming
Tutorial is designed to teach the C programming language to people who
have never programmed before.  The reader is expected to have basic
computer literacy. Numerous practice exercises and answers are
supplied. 
@c Row 1, Column 2
@tab 
@strong{The LaTeX Reference Manual}@*@strong{by The Indian TeX
Users Group}@*@emph{1-882114-70-1, $30.00}@*@emph{Perfect bound, trade
paper}@*@emph{Approx. 250 pages}@*@emph{Publication Date: October
2002}@*This book is an introductory manual for LaTeX.  It is a
comprehensive introduction to the basic concepts of mark-up languages,
what LaTeX is, and how to apply it. It covers a wide range of usages
including typesetting mathematical formulas and creating
cross-references, indexes, tables, and bibliographic databases.  @*@ @
@ @ @ @ @ @ @ @ @ @ @bullet{}@ @ @ @ @ @ @ @ @bullet{}@ @ @ @ @ @ @ @
@bullet{}@*@ @ @ @emph{GNU Press is an imprint of the Free Software
Foundation.}@*@ @ @emph{Examination copies for course adoption are
available at 50% off list price. Desk copies of GNU Press titles
adopted for classroom use are available gratis. All requests should be
made on department letterhead and include a bookstore purchase
order.@*@ @ @ Resellers, please contact us directly for ordering
information.@*@ @ The Free Software Foundation is a registered 501(c)(3)
charity in the USA and donations are both tax-deductible and
appreciated. Please visit our Web site www.gnu.org to learn more about
our organization and our efforts for software freedom.}
@c Row 2, Column 1
@c @item
@c @strong{The GNU C Programming Tutorial}@*@strong{by Mark Burgess & Ron
@c Hale-Evans}@*@strong{Edited by Joshua Gay}@*@emph{1-882114-61-2,
@c apx. $39.00}@*@emph{Lay flat, trade paper}@*@emph{Approx. 350
@c Pages}@*@emph{Publication Date: September 2002}@*The GNU C Programming
@c Tutorial is designed to teach the C programming language to people who
@c have never programmed before.  The reader is expected to have basic
@c computer literacy. Numerous practice exercises and answers are
@c supplied. 
@end multitable
@page

@c ******************PHILOSOPHY OF SOFTWARE FREEDOM *****************
@image{gnu_press_ads/philoseries,4.8in,1.45in}

@multitable {Column 1 length is this long 0 0 000} {Column 2 length is this long 0 0 000}

@c Row 1, Column 1

@item 
@strong{Free Software, Free Society:}@*@strong{Selected Essays of
}@*@strong{Richard M. Stallman}@*@strong{Introduction by Lawrence
Lessig}@*@strong{Edited by Joshua Gay}@*@emph{1-882114-98-1,
$24.95}@*@emph{Hard Cover Edition with dust jacket}@*@emph{Publication
Date: October 1, 2002}@*@emph{Category: Ethics, Law, Computers}@*The
intersection of ethics, law and computer software is the subject of
this collection of essays and speeches by MacArthur Fellow
Dr. Richard M. Stallman. He takes a critical look at the social uses
of software and business's abuse of copyright law and patents when
applied to computer software programs. Lawrence Lessig, the author of
two well known books on this same topic, writes the
introduction.@*@*@*@emph{RMS is the leading philosopher of
software. You may dislike some of his attitudes, but you cannot avoid
his ideas}@dots{}@emph{This book needs to be widely circulated and
widely read.} @*@strong{Peter Salus}

@c Row 1, Column 2
@tab
@strong{Software Freedom: An Introduction}@*@strong{by Robert
J. Chassell}@*@emph{1-882114-95-7, $22.95 (Estimate)}@*@emph{Hard
Cover Edition with dust jacket}@*@emph{Publication Date:
February 2003}@*@emph{Category: Business, Law, Computers}@*This book is
designed to explain the free software philosophy to business people
and other interested non-technical persons. The author will focus on
the economic and business conundrums of how an organization can make
money from software that is freely distributable.

@c Row1, Column 2 Continued

@*@*@strong{[Still Untitled]}@*@strong{by Miriam
Rainsford}@*@emph{1-882114-96-5, $24.95 (Estimate)}@*@emph{Hard Cover
Edition with dust jacket}@*@emph{Publication Date: September 2003
(Estimate)}@*@emph{Category: Music, Law, Computers}@*The author is a PhD
candidate in Electronic Music Composition at the University of
London. The book will discuss how sharing has always existed in music
composition, and how the concept of free software can apply to the
musical world.
@end multitable
@page

@c ****************  GNU C Language Related Manuals  ****************
@image{gnu_press_ads/gnuc,4.8in,1.45in}

@multitable {Column 1 length is this long 0 0 000} {Column 2 length is this long 0 0 000}

@c Row 1, Column 1
@item
@strong{GNU Make: A Program for}@*@strong{Directed Recompilation}@*@strong{by
Richard M. Stallman}@*@strong{and Roland McGrath}@*@emph{1-882114-82-5,
$20.00}@*@emph{January 2002, 196 Pages}@*@emph{Trade Paper, Lay Flat
Binding}@*The GNU Make manual, written by the program's original
authors, is the definitive tutorial. It also includes an introductory
chapter for novice users.

@c Row 1, Column 2
@tab
Ninth Edition!@*@strong{Debugging with GDB:}@*@strong{The GNU Source-Level
Debugger}@*@strong{by Stallman, Pesch, Shebs, et
al.}@*@emph{1-882114-88-4, $25.00}@*@emph{January 2002, 346
Pages}@*@emph{Trade Paper, Lay Flat Binding}@*Written for programmers
by the principal author and maintainers of the GDB program. Designed
so that readers can start using GDB after reading just the first
chapter


@c Row 2, Column 1
@item
@strong{The GNU C Library}@*@strong{Reference Manual}@*@strong{by S. Loosemore
with Stallman, et al.}@*@emph{1275 Pages in Two
Volumes}@*@emph{1-882114-54-X}@*@emph{$60.00 per
2-volume set}@*@emph{July 2001; For glibc version 2.2.x}@*@emph{Trade
Paper, Lay Flat Binding}@*This manual is the canonical guide to the
GNU implementation of the standard C libraries for system
administrators and programmers. It covers high-and-low level
interfaces, function specifications, code examples, usage
recommendations.

@c Row 2, Column 2
@tab
@strong{Using & Porting GNU CC}@*@strong{by Richard
M. Stallman}@*@emph{1-882114-38-8, $35.00}@*@emph{July 1999; for
Ver. 2.95., 588 Pages}@emph{Trade Paper, Lay Flat Binding}@*This
thorough reference guide shows how to install, run, debug, configure
and port the GNU Compiler Collection.
@end multitable
@page

@c ****************  GNU PRESS BACKLIST *****************************
@image{gnu_press_ads/gnubacklist,4.8in,1.45in}

@multitable {Column 1 length is this long 0 0 000} {Column 2 length is this long 0 0 000}

@c Row 1, Column 1
@item
@strong{The GNU Emacs Lisp Reference Manual}@*@strong{by Lewis,
LaLiberte, Stallman, et al.}@*@emph{974 Pages in Two
Volumes}@*@emph{1-882114-73-6}@*@emph{$60.00 per
2-volume set}@*@emph{May 2000; For Emacs V21 and below}@*@emph{Trade
Paper, Lay Flat Binding}@*This edition is completely revised to cover
Emacs Version 21, with an appendix noting differences for Emacs
Version 20. It also includes an introductory section for programmers
who are new to Lisp.

@c Row 1, Column 1 CONTINUED!!
@*@strong{Texinfo:}@*@strong{The GNU Documentation Format}@*@strong{by Robert
J. Chassell}@*@strong{and Richard M. Stallman}@*@emph{1-882114-67-1,
$25.00}@*@emph{Sept. 1999, for Ver. 4, 260 Pages}@*@emph{Trade Paper,
Lay Flat Binding}@*This tutorial is the authoritative text for
the official documentation formatting language used for all GNU
Project manuals. It assumes no previous Texinfo knowledge and includes
many examples and exercises.

@c Row 1, Column 2
@tab
Easy to Install!@*@strong{GNU Software for MS-Windows and
MS-DOS}@*@strong{by Hagerty, Weisshaus &
Zaretskii}@*@emph{1-882114-57-4, $35.00}@*@emph{June 2001, 150 pages with
CD}@*@emph{Trade Paper, Perfect Bound}@*The CD contains a collection
of executables and source code for popular GNU programs that run on a
Microsoft Windows machine. The accompanying book contains a detailed
installation guide. This second edition is updated for Windows ME and
NT, as well as being backwards-compatible for Windows 2000, 98, 95,
and 3.x. It can also be used on MS-DOS Versions 4 and up.@*@*Programs
include: The DOS and Windows versions of our popular GNU C and C+
Compiler, DJGPP and Cygwin; a full-sized Emacs, our popular editor;
the Perl programming language; the multi-lingual GNU Debugger, GDB;
GNU Make, our popular automated update compiler utility; Gzip, a
file-compression program; and Bash, a versatile shell.
@end multitable
@page

@c ****************  GNU PRESS BACKLIST *****************************
@multitable {Column 1 length is this long 0 0 000} {Column 2 length is this long 0 0 000}

@c Row 1, Column 1
@item
@strong{The Bison Manual: Using the YACC Compatible Parser
Generator}@*@strong{by Charles Donnelly}@*@strong{and Richard
M. Stallman}@*@emph{1-882114-44-2, $20.00}@*@emph{June 2002, for Ver
1.35, 104 Pages}@*@emph{Trade Paper, Lay Flat Binding}@*This manual
functions as both a tutorial and a reference guide for GNU Bison. It
also includes material on the theory of parser generators and the
particular algorithms used by Bison. The reader is assumed to already
know the C programming language, but no prior knowledge about parser
generators is assumed.

@c Row 1, Column 2
@tab
@strong{Flex: The Lexical Scanner Generator}@*@strong{by
G.T. Nicol}@*@emph{128 Pages, plus detachable Quick Reference
Card}@*@emph{1-882114-21-3, $20.00}@*@emph{February 1992, for Flex
Version 2.3.7}@*@emph{Plastic comb spine; no shrink-wrap}@*Primarily a
reference manual, but also has an introduction to Flex. Numerous
examples and formulas are provided.

@c Row 2, Column 1
@item 
@strong{The Termcap Manual: The Termcap}@*@strong{Library and
Database}@*@strong{by Richard M. Stallman}@*@emph{1-882114-87-6,
$15.00}@*@emph{August 1997, 3rd Edition, 68 Pages}@*@emph{Plastic comb
spine; no-shrink-wrap}@*This manual is for programmers who want to do
terminal-independent character-based display output. It is primarily a
reference guide with a few examples.



@end multitable


    @tex
    {\globaldefs = 1 \textfonts}
    @end tex
